kind: Service
apiVersion: v1
metadata:
  name: msa-trace
spec:
  type: NodePort
  selector:
    app: msa-trace
  ports:
  - protocol: TCP
    port: 9411
    nodePort: 31400
    targetPort: 9411
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msa-trace
  labels:
    app: msa-trace
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-trace
  template:
    metadata:
      labels:
        app: msa-trace
        version: "1.0.2"
    spec:
      hostname: trace
      subdomain: msa-trace
      containers:
      - name: msa-trace
        image: docker.gsp.sicc.co.kr/trace:1.0.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: spring.cloud.config.uri
          value: http://msa-config.development.svc.cluster.local:8888
        ports:
        - name: http
          containerPort: 9411